version: '3'
services:
  ipfsA:
    image: ipfs/go-ipfs:v0.4.21
    container_name: "ipfsA"
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    volumes:
      - ./data/ipfsA:/data/ipfs/ 
  clusterA:
    image: ipfs/ipfs-cluster:v0.11.0
    container_name: "ipfs-cluster-A"
    environment:
      IPFS_API: "/ip4/${HOST_IP}/tcp/5001"
      IPFS_BOOTSTRAP_RM_ALL: "true"
    ports:
      - 5080:8080
    depends_on:
      - ipfsA 
    volumes:
      - ./data/clusterA:/data/ipfs-cluster
  ipfsB:
    image: ipfs/go-ipfs:v0.4.21
    container_name: "ipfsB"
    ports:
      - 6001:4001
      - 7001:5001
    volumes:
      - ./data/ipfsB:/data/ipfs/ 
  clusterB:
    image: ipfs/ipfs-cluster:v0.11.0
    container_name: "ipfs-cluster-B"
    environment:
      IPFS_API: "/ip4/${HOST_IP}/tcp/7001"
      IPFS_BOOTSTRAP_RM_ALL: "true"
    ports:
      - 6080:8080
    depends_on:
      - ipfsB
    volumes:
      - ./data/clusterB:/data/ipfs-cluster
  ipfsC:
    image: ipfs/go-ipfs:v0.4.21
    container_name: "ipfsC"
    ports:
      - 8001:4001
      - 9001:5001
    volumes:
      - ./data/ipfsC:/data/ipfs/ 
  clusterC:
    image: ipfs/ipfs-cluster:v0.11.0
    container_name: "ipfs-cluster-C"
    environment:
      IPFS_API: "/ip4/${HOST_IP}/tcp/9001"
      IPFS_BOOTSTRAP_RM_ALL: "true"
    ports:
      - 7080:8080
    depends_on:
      - ipfsC
    volumes:
      - ./data/clusterC:/data/ipfs-cluster